### ISSUE TITLE
License in PyPI

### ISSUE THREAD

**Issue by lyovushka** [santosh-d3vpl3x/duckdb_extensions#7]
I tried to procure the PyPI packages internally, and got an error that license is missing. Would it be possible to fix this issue?

Thanks!

**Comment by santosh-d3vpl3x** [comment]
I have made some license related changes in this pre: https://pypi.org/project/duckdb-extension-spatial/1.1.3a1/

Can you check if that is sufficient for you?

**Comment by lyovushka** [comment]
Yeah was able to procure it. Thank you very much!

**Comment by santosh-d3vpl3x** [comment]
Direct tracking link: #34

https://github.com/santosh-d3vpl3x/duckdb_extensions/issues/34

**Comment by santosh-d3vpl3x** [comment]
Following up here: this has now been addressed and shipped.

- Tracking issue: #34
- Implemented on `main`: commit `305dacc`
- Clarified wrapper-vs-binary licensing in docs/metadata and added maintainer verification guardrails.

Details are summarized in #34: https://github.com/santosh-d3vpl3x/duckdb_extensions/issues/34#issuecomment-3979735403
